run:
	python3 CountWordDocuments.py space.json

runText:
	python3 CountWordDocuments.py spaceText.json

run_file:
	python3 CountWordDocuments.py space.json > countWordDocuments_result.txt 

runText_file:
	python3 CountWordDocuments.py spaceText.json > countWordDocuments_result.txt 