run:
	python3 SimpsonHappiness_mr.py simpsons_script_lines.csv

runText:
	python3 SimpsonHappiness_mr.py simpsons_script_lines_text.csv

run_file:
	python3 SimpsonHappiness_mr.py simpsons_script_lines.csv > simpsonHappiness_result.txt 

runText_file:
	python3 SimpsonHappiness_mr.py simpsons_script_lines_text.csv > simpsonHappiness_result.txt 